// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpSYKPxkxNju0ys0nH3mdd3NPrTdyhl8s',
    appId: '1:955095323922:web:ec77c877076c5ed0064fcb',
    messagingSenderId: '955095323922',
    projectId: 'phone-auth-test-df0a8',
    authDomain: 'phone-auth-test-df0a8.firebaseapp.com',
    storageBucket: 'phone-auth-test-df0a8.appspot.com',
    measurementId: 'G-R3JQ8XLFVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUN1r0VxaXYRc51med94vQfJxbGDHFWoE',
    appId: '1:955095323922:android:9867c6213645bd3d064fcb',
    messagingSenderId: '955095323922',
    projectId: 'phone-auth-test-df0a8',
    storageBucket: 'phone-auth-test-df0a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLWMsUg7d21h1c0jgNqKQiru94rmK6YrY',
    appId: '1:955095323922:ios:aa1bea2fc6ec3d40064fcb',
    messagingSenderId: '955095323922',
    projectId: 'phone-auth-test-df0a8',
    storageBucket: 'phone-auth-test-df0a8.appspot.com',
    iosClientId: '955095323922-tio57rvr01ndlqri6afcvk61adnup5ts.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebasePhoneAuthTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLWMsUg7d21h1c0jgNqKQiru94rmK6YrY',
    appId: '1:955095323922:ios:d0b6a363ee106697064fcb',
    messagingSenderId: '955095323922',
    projectId: 'phone-auth-test-df0a8',
    storageBucket: 'phone-auth-test-df0a8.appspot.com',
    iosClientId: '955095323922-16g22da928lvn7mf7hev2tgfiih72ki3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebasePhoneAuthTest.RunnerTests',
  );
}
